services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${USER_POSTGRES}
      POSTGRES_PASSWORD: ${PASSWORD_POSTGRES}
      POSTGRES_DB: ${DB_POSTGRES}
    ports:
      - "5433:5432"
    volumes:  # Persistencia de datos
      - postgres_data:/var/lib/postgresql/data

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${DB_POSTGRES}
      - DB_POSTGRESDB_USER=${USER_POSTGRES}
      - DB_POSTGRESDB_PASSWORD=${PASSWORD_POSTGRES}
      - N8N_HOST=0.0.0.0 
      - N8N_PORT=5678
    depends_on:
      - postgres

  ollama:
    image: ollama/ollama
    environment:
    - OLLAMA_MODELS=llama3:8b-instruct-q4_0  # Descarga automática
    ports:
      - "11434:11434"
    volumes:  # Persistencia de modelos descargados
      - ollama_data:/root/.ollama
    

  openwebui:
    image: ghcr.io/open-webui/open-webui:main   # ajustar según tag
    ports:
      - "3000:8080"
    environment:
    # Configuración básica
      - WEBUI_NAME="UNLA Asistente Virtual Académico"

      # Configuración ESSENCIAL de modelos
      - OLLAMA_BASE_URL=http://ollama:11434
      # - DEFAULT_MODEL=llama3:8b-instruct-q4_0

      # Variables CLAVE para mostrar modelos
      - ENABLE_LOCAL_MODEL_FILTER=true  # Permite ver todos los modelos
      - SHOW_LOCAL_MODELS=true           # Muestra modelos locales

      # ===== CONFIGURACIÓN OPENROUTER =====
      #- OPENAI_API_BASE_URL=https://openrouter.ai/api/v1
      #- OPENAI_API_KEY=${OPENROUTER_API_KEY}
      #- ENABLE_OPENAI_API=true

      # LIMITAR MODELOS DISPONIBLES (empezando por el más barato)
      # - MODEL_FILTER_LIST=gpt-4.1-nano

      # Configuración de autenticación (IMPORTANTE)
      - WEBUI_AUTH=false   # Desactiva autenticación completamente
      - ENABLE_SIGNUP=false                    # Desactiva registro de nuevos usuarios
      - DEFAULT_USER_ROLE=user                # Rol por defecto para usuarios
      - ENABLE_LOGIN_FORM=false               # Mantén esto en true inicialmente

      # Configuración para el asistente académico
      - ENABLE_COMMUNITY_SHARING=false        # Desactiva compartir chats
      - ENABLE_MESSAGE_RATING=true            # Permite calificar respuestas (útil para métricas)

      # Configuración de interfaz
      - DEFAULT_LOCALE=es                     # Interfaz en español
      - SHOW_ADMIN_DETAILS=false             # Oculta detalles de admin a usuarios
      - ENABLE_WEBSEARCH=false             # Desactivar búsqueda web. Evita que el asistente busque información externa fuera de tu base de datos académica
      - ENABLE_CHAT_DOWNLOAD=false         # Sin descarga de chats. Evita que se descarguen conversaciones con datos de otros estudiantes
      - ENABLE_RAG_WEB_LOADER=false        # Sin RAG web. Desactiva la capacidad de cargar documentos web para RAG (Retrieval Augmented Generation). Evita que se puedan subir URLs o documentos externos para procesar
      
     
    volumes:
      - /open_webui/openwebui_data:/app/backend/data
    depends_on:
      - ollama

# Volúmenes para persistencia
volumes:
  postgres_data:
  ollama_data:
  openwebui_data: