FROM ghcr.io/open-webui/open-webui:v0.6.29

# Copia tu logo de la UNLA al directorio estático 
COPY assets/unla-favicon.png /app/backend/open_webui/static/favicon.png
COPY assets/unla-favicon.png /app/build/static/favicon.png
COPY assets/unla-favicon.png /app/build/favicon.png

COPY assets/unla-favicon.svg /app/backend/open_webui/static/favicon.svg
COPY assets/unla-favicon.svg /app/build/static/favicon.svg
COPY assets/unla-favicon.svg /app/build/favicon.svg 

COPY assets/unla-favicon.ico /app/backend/open_webui/static/favicon.ico
COPY assets/unla-favicon.ico /app/build/static/favicon.ico
COPY assets/unla-favicon.ico /app/build/favicon.ico 

